let giomenu = [
  giomenu_early_mornin_fixins = [
    { title: 'Early Mornin Fixins' },
    { name: 'Sharon Sunrise', description: 'Sharon Sunrise', price: 6.95 },
    { name: 'JR Jumbo', description: 'JR Jumbo', price: 8.95 },
    { name: 'Jackie Stack', description: 'Jackie Stack', price: 5.95 },
    { name: 'French Toast', description: 'French Toast', price: 5.95 },
    { name: 'Harold Special', description: 'Harold Special', price: 2.95 },
    { name: 'Cheese Omelet', description: 'Cheese Omelet', price: 3.95 },
    { name: 'Supreme Omelet', description: 'Supreme Omelet', price: 7.95 },
    { name: 'Biscuit & Sausage Gravy', description: 'Biscuit & Sausage Gravy', price: 2.95 }
  ],
  giomenu_shared_plates = [
    { title: 'Shared Plates' },
    { name: 'Onion Petals', description: '', price: 3.95 },
    { name: 'Mozz Stix', description: '', price: 4.95 },
    { name: 'Jalepeno Stix', description: '', price: 4.95 },
    { name: 'Breaded Mushrooms', description: '', price: 4.95 },
    { name: 'Fried Green Tomatoes', description: '', price: 5.95 },
    { name: 'Fried Pickle Chips', description: '', price: 5.95 },
    { name: 'Battered Zuchini Strips', description: '', price: 6.95 },
    { name: 'Breaded or Naked Chicken Wings', description: '', price: 3.95 },
    { name: 'Chicken Wings', description: 'Chicken Wings Tossed in buffalo, honey hot, bbq, or general tso', price: 4.95 },
    { name: 'Chicken Tenders', description: '', price: 5.95 },
    { name: 'Chicken Parm', description: '', price: 7.95 },
    { name: 'Pizza Burger', description: '', price: 4.95 },
    { name: 'Bacon OR Chili Cheese Fries (small)', description: '', price: 6.95 },
    { name: 'Bacon OR Chili Cheese Fries (large)', description: '', price: 8.95 }
  ],
  giomenu_farm_to_table_burgers = [
    { title: 'Farm to Table Burgers' },
    { name: 'Hamburger', description: 'Fresh angus beef, topped with ketchup, mustard, onion, pickle, lettuce, tomato & mayo', price: 4.50 },
    { name: 'Double Hamburger', description: 'Fresh angus beef, topped with ketchup, mustard, onion, pickle, lettuce, tomato & mayo', price: 7.50 },
    { name: 'Cheeseburger', description: 'Fresh angus beef, topped with ketchup, mustard, onion, pickle, lettuce, tomato & mayo', price: 4.95 },
    { name: 'Double Cheeseburger', description: 'Fresh angus beef, topped with ketchup, mustard, onion, pickle, lettuce, tomato & mayo', price: 7.95 },
    { name: 'Bacon Cheeseburger', description: 'Fresh angus beef, topped with ketchup, mustard, onion, pickle, lettuce, tomato & mayo', price: 5.95 },
    { name: 'Double Bacon Cheeseburger', description: 'Fresh angus beef, topped with ketchup, mustard, onion, pickle, lettuce, tomato & mayo', price: 8.95 },
    { name: 'Mountaineer Hero', description: 'Mozzarella cheese, grilled onions, mushrooms & brown gravy', price: 6.95 },
    { name: 'Wimpy', description: 'Cheddar jack cheese, bacon, grilled onions, mushrooms & garlic aioli', price: 6.95 }
  ],
  giomenu_sides = [
    { title: 'Sides' },
    { name: 'French Fries', description: '', price: 2.95 },
    { name: 'Cottage Cheese', description: '', price: 2.95 },
    { name: 'Slaw', description: '', price: 2.95 },
    { name: 'Peaches', description: '', price: 2.95 },
    { name: 'Pineapple', description: '', price: 2.95 },
    { name: 'Veggies', description: '', price: 2.95 },
    { name: 'Onion Rings', description: '', price: 3.95 },
    { name: 'Sweet Potato Fries', description: '', price: 3.95 },
    { name: 'Sidewinder Fries', description: '', price: 3.95 },
    { name: 'Tossed Salad', description: '', price: 3.95 },
    { name: 'Mac n Cheese', description: '', price: 4.95 },
  ],
  giomenu_salads = [
    { title: 'Salads' },
    { name: 'Antipasta', description: 'olives, banana peppers, American & mozzarella cheese, tomatoes, green peppers, onions, ham, pepperoni, egg & topped with homemade croutons', price: 9.95 },
    { name: 'Salmon', description: '8oz atlantic salmon, tomatoes, onions, green peppers & topped with homemade croutons, mozzarella cheese & french fries', price: 16.95 },
    { name: 'Grilled Chicken', description: 'tomatoes, onions, green peppers & topped with homemade croutons, mozzarella cheese & french fries', price: 9.95 },
    { name: 'Crispy Chicken', description: 'tomatoes, onions, green peppers & topped with homemade croutons, mozzarella cheese & french fries', price: 9.95 },
    { name: 'Shaved Ribeye', description: 'tomatoes, onions, green peppers & topped with homemade croutons, mozzarella cheese & french fries', price: 9.95 }
  ],
  giomenu_dinn_dinn = [
    { title: 'Dinn Dinn' },
    { name: 'Spaghetti, side salad & garlic toast', description: 'Spaghetti with a side salad & garlic toast and two sides.', price: 10.95 },
    { name: 'Country Fried Steak', description: 'Country fried steak and two sides', price: 12.95 },
    { name: 'Hamburger Steak', description: 'Hamburger steak smothered with grilled onions, mushrooms and brown gravy and two sides', price: 12.95 },
    { name: 'Liver and Onions', description: 'Liver and onions and two sides', price: 12.95 },
    { name: 'Shrimp', description: 'Shrimp - breaded or grilled w/fries & slaw and two sides', price: 12.95 },
    { name: 'Chicken Tenders', description: 'Chicken Tenders and two sides', price: 12.95 },
  ],
  giomenu_farm_and_sea = [
    { title: 'Farm and Sea' },
    { name: '12 oz Center Cut Ribeye', description: '12 oz center cut ribeye and two sides', price: 22.95 },
    { name: '18 oz Center Cut NY Strip', description: '18 oz center cut NY strip and two sides', price: 19.95 },
    { name: '8 oz Atlantic Salmon', description: 'Atlantic salmon cajun dry rub or sesame ginger glaze and two sides', price: 18.95 }
  ],
  giomenu_sammiches = [
    { title: 'Sammiches' },
    { name: 'Giovanni Special', description: '', price: 12.95 },
    { name: 'Grilled Chicken', description: '', price: 12.95 },
    { name: 'Fried Fish', description: '', price: 12.95 },
    { name: 'Chicken Salad', description: '', price: 12.95 },
    { name: 'BLT', description: '', price: 12.95 },
    { name: 'Ham & Cheese', description: '', price: 12.95 },
    { name: 'Ribeye Steak', description: '', price: 12.95 },
    { name: 'Grilled Cheese', description: '', price: 12.95 },
    { name: 'Club', description: '', price: 12.95 },
    { name: 'Hot Roast Beef & Country Fried Steak', description: '', price: 12.95 },
    { name: 'Hot Dog', description: '', price: 2.25 },
    { name: 'Slaw Dog', description: '', price: 2.95 },
  ],
  giomenu_pizza_and_calzones = [
    { title: 'Pizza and Calzones' },
    { name: '5 Toppings Full Zone', description: '', price: 10.95 },
    { name: '1 Topping Full Zone', description: '', price: 7.95 },
    { name: '5 Toppings Half Zone', description: '', price: 7.95 },
    { name: '1 Topping Half Zone', description: '', price: 5.95 },
    { name: '5 Toppings 12x16in Rectangle Pizza', description: '', price: 19.95 },
    { name: '1 Topping 12x16in Rectangle Pizza', description: '', price: 13.95 },
    { name: '5 Toppings 12in Round Pizza', description: '', price: 13.95 },
    { name: '1 Topping 12in Round Pizza', description: '', price: 9.95 },
    { name: '5 Toppings 4-slice Half Pizza', description: '', price: 7.95 },
    { name: '1 Topping 4-slice Half Pizza', description: '', price: 5.95 },
    { name: '5 Toppings Cauliflower GF/Low Carb', description: '', price: 13.95 },
    { name: '1 Topping Cauliflower GF/Low Carb', description: '', price: 9.95 }
  ]
];
